[package]
name = "marlu"
version = "0.3.1"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>",
           "Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>"]
edition = "2021"
rust-version = "1.56"
license = "MPL-2.0"
readme = "README.md"
description = "Convenience Rust code that handles coordinate transformations, Jones matrices, I/O. for the Murchison Widefield Array (MWA) radio telescope. Previously known as mwa_rust_core"
repository = "https://github.com/MWATelescope/marlu"
homepage = "https://github.com/MWATelescope/marlu"
keywords = ["radioastronomy", "mwa", "astronomy", "aoflagger", "cotter"]
categories = ["science"]
exclude = ["tests/*", ".vscode/*", ".github/*", ".talismanrc"]

[features]
default = ["io", "mwalib"]

# Provide IO code. Pulls in heavy dependencies like rubbl.
io = ["rubbl_core", "rubbl_casatables"]

# Provide CUDA convenience code
cuda = ["cuda-runtime-sys"]

# Compile various C libraries statically.
erfa-static = ["erfa-sys/static"]
cfitsio-static = ["mwalib/cfitsio-static"]
cuda-static = []
all-static = ["erfa-static", "cfitsio-static", "cuda-static"]

[dependencies]
cfg-if = "1.0.*"
erfa-sys = "0.1.*"
flate2 = "1.0.*"
hifitime = "^2.3.0"
itertools = "0.10"
lazy_static = "1.4.*"
log = "0.4.*"
ndarray = { version = ">=0.15.4,<0.16", features = ["rayon"] }
num-complex = "0.4.*"
num-traits = "0.2.*"
rayon = "~1"
tar = "0.4.*"
thiserror = "1.0.*"
mwalib = { version = ">=0.12.0", optional = true }

rubbl_core = { version = "0.3.0", optional = true }
rubbl_casatables = { version = "0.6.0", optional = true }

cuda-runtime-sys = { version = "0.3.0-alpha.1", optional = true }

[dev-dependencies]
approx = { version = "0.5.*", features = ["num-complex"] }
criterion = "0.3.*"
glob = "0.3"
tempfile = "3.3"
ndarray = { version = ">=0.15.4,<0.16", features = ["approx-0_5"] }
serial_test = "0.5.*"

[[bench]]
name = "bench_misc"
harness = false

[[bench]]
name = "bench_io"
harness = false
