[package]
name = "marlu"
version = "0.2.2"
authors = ["Christopher H. Jordan <christopherjordan87@gmail.com>",
           "Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>"]
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
description = "Convenience Rust code that handles coordinate transformations, Jones matrices, I/O. for the Murchison Widefield Array (MWA) radio telescope. Previously known as mwa_rust_core"
repository = "https://github.com/MWATelescope/marlu"
homepage = "https://github.com/MWATelescope/marlu"
keywords = ["radioastronomy", "mwa", "astronomy", "aoflagger", "cotter"]
categories = ["science"]
exclude = ["tests/*", ".vscode/*", ".github/*", ".talismanrc"]

[features]
default = ["mwalib"]
erfa-static = ["erfa-sys/static"]
cfitsio-static = ["mwalib/cfitsio-static"]
all-static = ["erfa-static", "cfitsio-static"]

[dependencies]
erfa-sys = "0.1.*"
flate2 = "1.0.20"
hifitime = "^2.3.0"
itertools = "0.10"
lazy_static = "1.4.0"
log = "0.4.*"
num-traits = "0.2.*"
rayon = "~1"
rubbl_core = "0.3.0"
rubbl_casatables = "0.6.0"
tar = "0.4.37"
thiserror = "1.0.*"
mwalib = { version = ">=0.12.0", optional = true }

# Needed to implement AbsDiffEq on the Jones type. Makes testing much easier!
# ndarray 0.14.* depends on approx 0.4.0, which in turn uses num-complex 0.3.0.
# Forcing the versions here means that ndarrays of complex numbers can be
# tested!
ndarray = { version = "0.14.*", features = ["approx"] }

[dev-dependencies]
criterion = "0.3.*"
tempfile = "3.2"

[[bench]]
name = "bench"
harness = false
