# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push, pull_request]

name: Generate Coverage report

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: mwatelescope/marlu:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install nightly toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="${HOME}/.cargo/bin:${PATH}"
          rustup set profile minimal
          rustup toolchain install nightly-2022-01-14 --component llvm-tools-preview
          rustup default nightly-2022-01-14

      - name: Install system and Cargo Packages
        run: |
          export PATH="${HOME}/.cargo/bin:${PATH}"
          apt-get update
          apt-get install -y lcov clang curl zip unzip libssl-dev jq liberfa-dev libcfitsio-dev
          cargo +nightly-2022-01-14 install cargo-llvm-cov
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Generate test lcov coverage into coverage/ dir
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTDOCFLAGS: "-Cpanic=abort"
          LLVM_PROFILE_FILE: json5format-%m.profraw
        run: |
          export PATH="${HOME}/.cargo/bin:${PATH}"
          mkdir -p coverage
          cargo +nightly-2022-01-14 llvm-cov --lib --lcov --output-path coverage/coverage.lcov

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
